import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "@next/font/local";
import "../app/global-styles/globalStyles.css";

export const metadata: Metadata = {
  title: "De Stonks",
  description: "Generated by create next app",
};

const Neue = localFont({
  src: [
    {
      path: "../../public/fonts/NeueMontreal-Light.otf",
      weight: "500",
    },
    {
      path: "../../public/fonts/NeueMontreal-Regular.otf",
      weight: "600",
    },
    {
      path: "../../public/fonts/NeueMontreal-Medium.otf",
      weight: "700",
    },
    {
      path: "../../public/fonts/NeueMontreal-Bold.otf",
      weight: "800",
    },
  ],
  variable: "--font-neue",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${Neue.variable} font-sans`}>{children}</body>
    </html>
  );
}
